WRP-9599: Updated dependencies for communication-server
enactjs/agate-apps pull request #276
Opened 2023-03-01 10:36 UTC by ion-andrusciac-lgp

### Checklist 

* [X] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [X] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Updated dependencies to their latest released version, and adapted code accordingly

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Updated `socket.io-client` and `roslib`, to match the `EIO` version for updated `socket.io` in `communication-server`

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-9599

### Comments

Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

2023-03-02 13:51 UTC, stanca-pop-lgp requested changes
Please check my comment.

2023-03-02 13:51 UTC, stanca-pop-lgp commented on communication-server/src/app.js
> +		origin: ['http://localhost:8080', "http://localhost:8081"],
Please change double quotes with single quotes.

2023-03-03 07:13 UTC, stanca-pop-lgp approved these changes

2023-03-03 09:39 UTC, daniel-stoian-lgp approved these changes

2023-03-08 08:06 UTC, merged