WRP-11631: Changed dynamic color change to run on the entire app
enactjs/agate-apps pull request #282
Opened 2023-03-23 11:03 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
 Changed dynamic color change to run on the entire app

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
 Changed dynamic color change to run on the entire app

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-11631

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian [daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com)

2023-03-24 13:32 UTC, stanca-pop-lgp requested changes

2023-03-24 13:32 UTC, stanca-pop-lgp commented on console/src/App/App.js
> +					<ThemeSettings onSelect={onSelect} onSendSkinSettings={sendSkinSettings} onToggleDynamicColor={onToggleDynamicColor} onToggleRealTime={handleRealState} realTime={realTime} prevIndex={prevIndex}
Please sort props.

2023-03-24 14:23 UTC, daniel-stoian-lgp commented on console/src/App/App.js
> +					<ThemeSettings onSelect={onSelect} onSendSkinSettings={sendSkinSettings} onToggleDynamicColor={onToggleDynamicColor} onToggleRealTime={handleRealState} realTime={realTime} prevIndex={prevIndex}
```suggestion
					<ThemeSettings onSelect={onSelect} onSendSkinSettings={sendSkinSettings} onToggleDynamicColor={onToggleDynamicColor} onToggleRealTime={handleRealState} prevIndex={prevIndex}  realTime={realTime} />
```

2023-03-27 07:07 UTC, stanca-pop-lgp approved these changes
LGTM

2023-03-28 16:10 UTC, adrian-cocoara-lgp approved these changes
LGTM

2023-03-28 16:10 UTC, merged